yatube/posts/urls.py
# posts/urls.py
from django.urls import path

from . import views

app_name = 'post'

urlpatterns = [
    path('', views.index, name='best_index'),
    path('group/<slug:slug>/', views.group_posts, name='group')
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='post'))
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
# Create your models here.

User = get_user_model()


class Post(models.Model):
    group = models.ForeignKey('Group',
                              blank=True,
                              null=True,
                              on_delete=models.CASCADE)
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='post'
    )


class Group(models.Model):
    title = models.TextField()
    slug = models.SlugField(max_length=255, unique=True)
    description = models.TextField()

    def __str__(self):
        return self.slug

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Group

# Create your views here.


def index(request):
    posts = Post.objects.order_by('-pub_date')[:10]
    template = 'post/index.html'
    title = 'Привет'
    context = {'posts': posts, 'title': title, }
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    template = 'post/group_list.html'
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, template, context)

yatube/templates/base.html
<!DOCTYPE html> 
<html lang="ru">          
  <head>       
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    {% load static %}
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{%static "img/fav/apple-touch-icon.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{%static "img/fav/favicon-32x32.png"%}">
    <link rel="icon" type="image/png" sizes="16x16" href="{%static "img/fav/favicon-16x16.png"%}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{%block title%} {{title}} {% endblock %} </title>
  </head>
  <body>       
    <header>
      <!-- Это тег шаблонизатора include, сюда будет включён код
      из файла includes/header.html -->
      {% include 'post/includes/header.html' %}
    </header>
    <main>
        {%block content%}{% endblock %}
    </main>
    <footer>
      {% include 'post/includes/footer.html' %} 
    </footer>
  </body>
</html> 

yatube/templates/post/group_list.html
{% extends 'base.html' %}
{% block title %} {{group}} {% endblock title %}
{% block content %}

<div class="container">
  <h1>{{group}}</h1>
  <p>
    {{ group.description }}
  </p>
{% for post in posts %}
  <article>
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>      
    <p>
      {{ post.text }}
    </p>         
  </article>
  <hr>
{% endfor %} 
{% endblock %}

yatube/templates/post/includes/footer.html
<footer class="page-footer font-small blue border-top">
    <div class="footer-copyright text-center py-3">© 2020 Copyright 
      <p><span style="color:red">Ya</span>tube</p> 
    </div>    
  </footer>

yatube/templates/post/includes/header.html
<!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
<!-- В дальнейшем тут будет создано полноценное меню -->    
<nav class="navbar navbar-light" style="background-color: lightskyblue">
<div class="container">
    <a class="navbar-brand" href={% url 'post:best_index' %}>
    {% load static %}
    <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
    <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
    <span style="color:red">Ya</span>tube
    </a>
</div>
</nav>    

yatube/templates/post/index.html
{% extends 'base.html' %}
{% block title %} {{ title }} {% endblock  %}>
{% block content %}
<div class="container">        
  <h1>Последние обновления на сайте</h1>
  {% for post in posts %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>{{ post.text }}</p>    
  {% if post.group %}
    <a href="{% url 'post:group' post.group%}">все записи группы</a>
  {% endif %} 
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %} 
</div>  
{% endblock content %}